### ISSUE TITLE
v0.5.4 install issues.

### ISSUE THREAD

**Issue by augur42** [SickChill/SickChillInstaller#27]
This is being run on Windows 10 Pro 1909 OS build 18363.1016
It took at least three goes at installing to figure what was going wrong. The only thing I didn't do was upon uninstalling I chose not to delete the C:\SickChill folder.

PortableGit was being installed to this location by default
C:\Users\{administrator}\AppData\Local\Temp\is-SBGAI.tmp\PortableGit
I had to manually change it to this for the install to not throw up a git.exe error
C:\SickChill\Git

The installer downloaded python 3.8.5 amd64 but failed to install it anywhere I could find, and I looked and searched.
I had to resort to going to python.org and installing https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64-webinstall.exe customising the install path (and adding it to PATH).
from
C:\Users\{user}\AppData\Local\Programs\Python\Python38
to
C:\SickChill\Python\

After that the service still failed to start and I had to manually edit nssm
from
"C:\SickChill\SickChill\SickBeard.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
to
"C:\SickChill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
although that might be my fault because I did have the service disabled as I run SickChill using a batch file so I can have multiple data directories

At this point it successfully started and after editing a batch file I could run SickChill with a specific data directory.

**Comment by Yoshi900** [comment]
I had to do exactly everything augur42 had to do. 
If anyone wants to get this working for them the nssm command is 
C:\SickChill\Installer>nssm edit sickchill

**Comment by miigotu** [comment]
Already fixed in installer release 0.5.7
